### Teste GET API Amizade GET

GET http://localhost:8080/api/v1/amizades


### Teste POST API Amizade POST

POST http://localhost:8080/api/v1/amizades
Content-Type: application/json 

{
    "solicitante": {
    "id": 1,
    "nome": "José da Silva Alterado",
    "email": "josesilva@gmail.com",
    "senha": "12345",
    "watchlist": []
  },
    "solicitado": {
    "id": 2,
    "nome": "José da Silva",
    "email": "josesilva@gmail.com",
    "senha": "12345",
    "watchlist": []
  },
    "status": "pendente"
}

### API Amizade - PUT 
PUT http://localhost:8080/api/v1/amizades/1
Content-Type: application/json 

{
    "solicitante": {
    "id": 1,
    "nome": "José da Silva Alterado",
    "email": "josesilva@gmail.com",
    "senha": "12345",
    "watchlist": []
  },
    "solicitado": {
    "id": 2,
    "nome": "José da Silva",
    "email": "josesilva@gmail.com",
    "senha": "12345",
    "watchlist": []
  },
    "status": "aceito"
}

### API Amizade - DELETE 
DELETE http://localhost:8080/api/v1/amizades/1
Content-Type: application/json