### Teste GET API Amizade GET

GET http://localhost:8080/api/v1/amizades


### Teste POST API Amizade POST

POST http://localhost:8080/api/v1/amizades
Content-Type: application/json 

{
    "solicitante": {
        "id": 1
    },
    "solicitado": {
        "id": 2
    },
    "status": "pendente"
}

### API Amizade - PUT 
PUT http://localhost:8080/api/v1/amizades/1
Content-Type: application/json 

{
    "solicitante": {
        "id": 1
    },
    "solicitado": {
        "id": 2
    },
    "status": "aceito"
}

### API Amizade - DELETE 
DELETE http://localhost:8080/api/v1/amizades/1
Content-Type: application/json